Repository arjunkesava/pr-size-labeller-test, pull requests merged in 2020-11, with the labels that each got.

#27 add 'test-file--800-lines'
  test-file--800-lines
Labels: size-XL

#26 add 'test-file--400-lines'
  test-file--400-lines
Labels: size-L

#24 add 'test-file--799-lines'
  test-file--799-lines
Labels: size-L

#19 add 'test-file--1-line'
  test-file--1-line
Labels: size-XS

#25 add 'test-file--399-lines'
  test-file--399-lines
Labels: size-M

#23 add 'test-file--100-lines'
  test-file--100-lines
Labels: size-M

#22 add 'test-file--99-lines'
  test-file--99-lines
Labels: size-S

#21 add 'test-file--50-lines'
  test-file--50-lines
Labels: size-S

#20 add 'test-file--49-lines'
  test-file--49-lines
Labels: size-XS

#28 test
  bin/pr-size.sh
Labels: size-M
